@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJpYXQiOjE2NzMxOTIxNDksImV4cCI6MTY3MzM2NDk0OX0.3X7fB7uNA7XQ9PntFDC0goHk6YR3djBInnagm_pdc0s

###
GET http://localhost:3001/bookclub/63fe17c2ee9bdea2cc48b642

###
GET http://localhost:3001/users


//--------------------------------------------------------------------------------


#EXAMPLES

###
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "denemeregister1",
    "password": "1",
    "email": "1@gmail.com"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "matar32",
    "password": "1"
}

###
POST http://localhost:3001/bookadd
Content-Type: application/json

{
  "name": "furkan",
  "author": "furkan",
  "description": "furkan zaten sacma sapan seyler okur :d",
  "image": "https://media.licdn.com/dms/image/C4D03AQHmHUh3pMXCzQ/profile-displayphoto-shrink_400_400/0/1640553030384?e=1683763200&v=beta&t=J3V2wfSVVBGOXxHz5THbyWnWYfRKvegvYubRQlVXDAI"
}





###
POST http://localhost:3001/bookclubadd
Content-Type: application/json

{
  "name": "matar",
  "genre": "philosophy",
  "description": "test description",
  "image": "https://binaries.templates.cdn.office.net/support/templates/tr-tr/lt66804846_quantized.png"
}


